server:
  port: 9090

spring:
  application:
    name: user-api

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

token:
  secret:
    key:
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
